from .save_text_node import NODE_CLASS_MAPPINGS as TEXT_MAPPINGS
from .save_text_node import NODE_DISPLAY_NAME_MAPPINGS as TEXT_NAMES

from .save_image_node import NODE_CLASS_MAPPINGS as IMAGE_MAPPINGS
from .save_image_node import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_NAMES

from .cinema_take_saver import NODE_CLASS_MAPPINGS as CINEMA_MAPPINGS
from .cinema_take_saver import NODE_DISPLAY_NAME_MAPPINGS as CINEMA_NAMES

from .save_video_node import NODE_CLASS_MAPPINGS as VIDEO_MAPPINGS
from .save_video_node import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_NAMES

from .filmmaker_multi_lora import NODE_CLASS_MAPPINGS as FILMMAKER_LORA_MAPPINGS
from .filmmaker_multi_lora import NODE_DISPLAY_NAME_MAPPINGS as FILMMAKER_LORA_NAMES

from .filmmaker_wrapped_nodes import NODE_CLASS_MAPPINGS as FILMMAKER_WRAP_MAPPINGS
from .filmmaker_wrapped_nodes import NODE_DISPLAY_NAME_MAPPINGS as FILMMAKER_WRAP_NAMES

from .filmclusive_shot_logger import NODE_CLASS_MAPPINGS as SHOT_LOGGER_MAPPINGS
from .filmclusive_shot_logger import NODE_DISPLAY_NAME_MAPPINGS as SHOT_LOGGER_NAMES

WEB_DIRECTORY = "./web"

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(TEXT_MAPPINGS)
NODE_CLASS_MAPPINGS.update(IMAGE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(CINEMA_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VIDEO_MAPPINGS)
NODE_CLASS_MAPPINGS.update(FILMMAKER_LORA_MAPPINGS)
NODE_CLASS_MAPPINGS.update(FILMMAKER_WRAP_MAPPINGS)
NODE_CLASS_MAPPINGS.update(SHOT_LOGGER_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(TEXT_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(CINEMA_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(FILMMAKER_LORA_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(FILMMAKER_WRAP_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(SHOT_LOGGER_NAMES)
