from .save_text_node import NODE_CLASS_MAPPINGS as TEXT_MAPPINGS
from .save_text_node import NODE_DISPLAY_NAME_MAPPINGS as TEXT_NAMES

from .save_image_node import NODE_CLASS_MAPPINGS as IMAGE_MAPPINGS
from .save_image_node import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_NAMES

from .cinema_take_saver import NODE_CLASS_MAPPINGS as CINEMA_MAPPINGS
from .cinema_take_saver import NODE_DISPLAY_NAME_MAPPINGS as CINEMA_NAMES

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(TEXT_MAPPINGS)
NODE_CLASS_MAPPINGS.update(IMAGE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(CINEMA_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(TEXT_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(CINEMA_NAMES)
